#!/bin/bash

# Get the directory of the script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Navigate to the project root (assuming the script is in the scripts folder)
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Define the output directory for the binaries
OUTPUT_DIR="$PROJECT_ROOT/bin"

# Clean the output directory
echo "Cleaning the output directory..."
rm -rf "$OUTPUT_DIR"

# Create the output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

echo ""
# Build for Windows (64-bit)
echo "Building for Windows (64-bit)..."
GOOS=windows GOARCH=amd64 go build -o "$OUTPUT_DIR/thwInventoryMerge.exe"

# Build for macOS (Intel)
echo "Building for macOS (Intel)..."
GOOS=darwin GOARCH=amd64 go build -o "$OUTPUT_DIR/thwInventoryMerge-amd64"

# Build for macOS (M1/M2)
echo "Building for macOS (M1/M2)..."
GOOS=darwin GOARCH=arm64 go build -o "$OUTPUT_DIR/thwInventoryMerge-arm64"
echo ""
echo "Builds completed."
echo "Binaries are located in the $OUTPUT_DIR directory."